### ISSUE TITLE
Warnings in commands

### ISSUE THREAD

**Issue by vishalraj82** [bmuschko/ckad-prep#7]
I am using the laest versions of minikube and kubectl on my ubuntu desktop. While practicing for [Configuration](https://github.com/bmuschko/ckad-prep/blob/master/2-configuration.md), I encountered to exceptions, that I would like to notify you.

For the command - `kubectl get serviceaccount backend-team -o yaml --export`, kubectl always complained of  - _Error: unknown flag: --export_

For the command - `kubectl run backend --namespace=ckad-prep --image=nginx --restart=Never --serviceaccount=backend-team`, kubectl warned of - _Flag --serviceaccount has been deprecated, has no effect and will be removed in the future_.

**Comment by bmuschko** [comment]
The examples of this repository are bound to the video-recorded course on O'Reilly that uses a specific version of Kubernetes. To ensure that videos match with the examples, I cannot update them without re-recording the course.

Please refer to the following repositories if you want to example that work with the newer versions of Kubernetes:

* https://github.com/bmuschko/ckad-crash-course
* https://github.com/bmuschko/ckad-study-guide
